// db/CatsCarsDatabase.kt
// CatsCarsCoins — spec 24.3.5. Complete file.
// Change from 24.2.5: version 2 — cats + cats_fts entities registered,
// AutoMigration(1, 2) generated by Room from the committed 1.json.
package com.icodeforyou.catscarscoins.db

import androidx.room3.AutoMigration
import androidx.room3.Database
import androidx.room3.RoomDatabase
import com.icodeforyou.catscarscoins.cats.data.CatDao
import com.icodeforyou.catscarscoins.cats.data.CatEntity
import com.icodeforyou.catscarscoins.cats.data.CatFtsEntity
import com.icodeforyou.catscarscoins.coins.data.CoinDao
import com.icodeforyou.catscarscoins.coins.data.CoinEntity

/**
 * The one app database (spec §5). Version history:
 * - v1: coins (Phase 2)
 * - v2: cats + cats_fts FTS4 shadow (Phase 3), via AutoMigration —
 *   new-table additions are exactly the case auto-migration proves
 *   mechanically: Room diffs the committed schemas/1.json against this
 *   declaration and generates the DDL, FTS virtual table and sync
 *   triggers included. No hand-written DDL to drift from Room's
 *   expectations.
 *
 * Room 3: androidx.room3 package; instantiation in the Koin module via
 * Room.databaseBuilder with the mandatory BundledSQLiteDriver.
 */
@Database(
    entities = [
        CoinEntity::class,
        CatEntity::class,
        CatFtsEntity::class,
    ],
    version = 2,
    exportSchema = true,
    autoMigrations = [
        AutoMigration(from = 1, to = 2),
    ],
)
abstract class CatsCarsDatabase : RoomDatabase() {

    abstract fun coinDao(): CoinDao

    abstract fun catDao(): CatDao
}